services:
  mysql:
    build:
      context: ./mysql
    container_name: mysql_container
    networks:
      - db_network
    volumes:
      - db_volume:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 3

  app:
    build: ./app
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./app/src:/app
    networks:
      - db_network
      - site_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4743/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  nginx:
    build: ./nginx
    depends_on:
      app:
        condition: service_healthy
    ports:
      - "5423:824"
    networks:
      - site_network

volumes:
  db_volume:

networks:
  db_network:
  site_network: